name: devopsfinal

services:
  client-frontend:
    image: agona-frontend:v1
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '3000:80'

  client-backend:
    image: agona-backend:v1
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db

  service-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2203
      POSTGRES_DB: hiphopdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped


  grafana:
    image: grafana/grafana:latest
    container_name: agona-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.9.4
    container_name: agona-loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yml
      - ./loki/wal:/loki/wal
      - ./loki/compactor:/loki/compactor       
      - ./loki/rules:/loki/rules
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.4
    container_name: agona-promtail
    volumes:
      - ./loki/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
volumes:
  db-data:
  grafana-storage: